<?php /** @var \Adcaptcha\Adcaptcha\Block\Adcaptcha\Config $block */ ?>
<?php /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */ ?>
<?php
$serializedAdcaptchaConfig= $block->getSerializedAdcaptchaConfig();
$scriptString = <<<script
        window.adcaptchaConfig = {$serializedAdcaptchaConfig};
script;
?>
<?= $secureRenderer->renderTag('script', [], $scriptString, false) ?>
